// All human-readable copy lives here. Written as UTF-8; do not edit with tools that
// re-encode non-ASCII text.

export const copy = {
  en: {
    docTitle: "Junyan Lin — Quantitative Finance, SMU",
    skip: "Skip to content",
    loc: "Singapore",
    langLabel: "中文",
    resume: "Resume",
    write: "Email",
    loaderLine: "Loading",
    rail: [
      ["01", "Intro", "#intro"],
      ["02", "Projects", "#work"],
      ["03", "Experience", "#practice"],
      ["04", "Skills", "#index"],
      ["05", "Contact", "#contact"],
    ],
    ticker: ["S&P Capital IQ", "DCF", "DDM", "P/E · P/B", "KYC / UBO", "IFRS spreading", "Sector briefs", "Excel models", "CFA Level I", "Bloomberg BMC"],
    heroKicker: "SMU · Quantitative Finance · Class of 2028",
    heroName: "Junyan Lin",
    heroAka: "Chris",
    heroPhotoCap: "Singapore · 2026",
    heroLead:
      "Third-year Quantitative Finance student at SMU, from Shenzhen and based in Singapore. Currently interning in corporate banking at Bank of China (Singapore), and into vibe coding — building things like this site. Outside that: films, basketball, and DJing hip-hop sets on the side.",
    heroNow: "Currently",
    heroNowBody: "Relationship Manager Intern, Global Corporate Banking, Bank of China (Singapore) · Aug–Nov 2026",
    heroCtaWork: "View projects",
    heroCtaNote: "Open the first project",
    aboutEyebrow: "02 — About",
    aboutTitle: "From Shenzhen, studying in Singapore. Into finance, and into building my own things with code.",
    aboutBody:
      "Currently interning in corporate banking at Bank of China (Singapore) — I work with financial statements, sector research and valuation. Every number in a set of accounts is a decision someone made; I like working back from the numbers to those decisions, and using them to help get the next one right. Off hours I build things: an AI resume tool, an AI tarot app, AI videos, and the site you're on right now.",
    figures: [
      ["School", "SMU, Quantitative Finance · 2024–2028"],
      ["Now", "Bank of China (Singapore) · Corporate banking intern"],
      ["Skills", "Financial analysis, valuation, vibe coding"],
      ["Languages", "Mandarin (native) · English (professional)"],
    ],
    aboutSchool: "Singapore Management University · Lee Kong Chian School of Business · Class of 2028",
    workEyebrow: "03 — Projects",
    workTitle: "Projects",
    workHint: "Four pieces of coursework from SMU and one personal project. Click one to open it.",
    workOpen: "Open project",
    practiceEyebrow: "04 — Experience",
    practiceTitle: "Experience",
    djEyebrow: "Off hours",
    djTitle: "DJ",
    djBody: "DJ is one of the things I do for fun. When I have time I pick up hip-hop and R&B sets — a semi-outdoor club on Sentosa, and New Year's Eve at a friend's bar.",
    bbEyebrow: "Also",
    bbTitle: "Basketball",
    bbBody: "Basketball is one of the things I can't really let go of. It's been how I stay in shape and blow off steam since I was eight. I had a basketball dream, put it down because of school and life, and I still love it.",
    indexEyebrow: "05 — Skills",
    indexTitle: "Skills and tools",
    contactEyebrow: "06 — Contact",
    contactTitle: "Get in touch",
    contactBody:
      "The easiest way to reach me is email — I usually reply within a day.",
    contactEmail: "Email",
    contactPhone: "Singapore",
    contactPhoneCn: "China",
    contactLi: "LinkedIn",
    contactWechat: "WeChat",
    copy: "Click to copy",
    copied: "Copied",
    footerNote: "Last updated September 2026",
    back: "Back",
    close: "Close",
    prevProject: "Previous",
    nextProject: "Next",
    metaCourse: "Course",
    metaWhen: "When",
    metaTeam: "Team",
    metaRole: "My part",
    keyNumbers: "Key numbers",
    cursorOpen: "Open",
  },
  zh: {
    docTitle: "林峻延 — 新加坡管理大学 量化金融",
    skip: "跳到正文",
    loc: "新加坡",
    langLabel: "EN",
    resume: "简历",
    write: "邮件",
    loaderLine: "加载中",
    rail: [
      ["01", "简介", "#intro"],
      ["02", "项目", "#work"],
      ["03", "经历", "#practice"],
      ["04", "技能", "#index"],
      ["05", "联系", "#contact"],
    ],
    ticker: ["S&P Capital IQ", "DCF", "DDM", "P/E · P/B", "KYC / 实控人", "IFRS 财报录入", "行业简报", "Excel 模型", "CFA 一级", "Bloomberg BMC"],
    heroKicker: "新加坡管理大学 · 量化金融 · 2028 届",
    heroName: "林峻延",
    heroAka: "Chris",
    heroPhotoCap: "新加坡 · 2026",
    heroLead:
      "新加坡管理大学量化金融大三，深圳人，现居新加坡。目前在中国银行新加坡分行做公司金融实习，也喜欢钻研 vibe coding，比如这个网站。此外还爱看电影、打篮球，也是个兼职 hip-hop DJ。",
    heroNow: "目前",
    heroNowBody: "中国银行（新加坡分行）环球公司金融部 · 客户经理实习生 · 2026.08–11",
    heroCtaWork: "查看项目",
    heroCtaNote: "打开第一个项目",
    aboutEyebrow: "02 — 关于我",
    aboutTitle: "深圳长大，新加坡读书。喜欢金融，也喜欢用代码把想法做出来。",
    aboutBody:
      "目前在中国银行做公司金融实习，平时接触财报、行业研究和估值这些。财报上每个数字背后都是一个人做过的决定；我喜欢从数字倒推那些决定，也喜欢用数字帮人把下一个决定做对。下班就自己捣鼓东西：做过 AI 改简历网站、AI 塔罗、剪 AI 视频，还有你正在看的这个站。",
    figures: [
      ["学校", "SMU 量化金融 · 2024–2028"],
      ["现在", "中国银行（新加坡）· 公司金融实习"],
      ["技能", "财报分析、估值、vibe coding"],
      ["语言", "中文（母语）· 英文（专业）"],
    ],
    aboutSchool: "新加坡管理大学 · 李光前商学院 · 2028 届",
    workEyebrow: "03 — 项目",
    workTitle: "项目",
    workHint: "四份新大的课程作品和一个个人项目。点开任意一个查看。",
    workOpen: "打开项目",
    practiceEyebrow: "04 — 经历",
    practiceTitle: "经历",
    djEyebrow: "业余",
    djTitle: "DJ",
    djBody: "DJ 也是我的兴趣爱好之一。闲暇的时候我会去做兼职 hip-hop、R&B DJ，在圣淘沙的半室外 club，也有在朋友酒吧的跨年夜上。",
    bbEyebrow: "还有",
    bbTitle: "篮球",
    bbBody: "篮球也是我人生中无法割舍的爱好之一。从 8 岁开始就是我锻炼身体、释放压力的最优解。有过篮球梦，也因为学业和现实原因放下过，但现在依旧热爱。",
    indexEyebrow: "05 — 技能",
    indexTitle: "技能与工具",
    contactEyebrow: "06 — 联系",
    contactTitle: "联系我",
    contactBody: "找我最快的方式是邮件，一般一天内回。",
    contactEmail: "邮箱",
    contactPhone: "新加坡",
    contactPhoneCn: "中国",
    contactLi: "领英",
    contactWechat: "微信",
    copy: "点击复制",
    copied: "已复制",
    footerNote: "2026 年 9 月更新",
    back: "返回",
    close: "关闭",
    prevProject: "上一个",
    nextProject: "下一个",
    metaCourse: "课程",
    metaWhen: "时间",
    metaTeam: "团队",
    metaRole: "我负责",
    keyNumbers: "关键数字",
    cursorOpen: "打开",
  },
}

export const experience = [
  {
    id: "boc",
    en: {
      role: "Relationship Manager Intern",
      org: "Bank of China (Singapore Branch)",
      unit: "Global Corporate Banking",
      dates: "Aug 2026 – Nov 2026",
      place: "Singapore",
      lead: "Credit-side support for the coverage team: sector research, credit due diligence, financial spreading and KYC.",
      points: [
        "Wrote sector briefs on Thailand data centres and on social media and digital advertising, on my own: value chain, market size and growth, competition, policy incentives, and the risks as a lender sees them. Used for sector coverage and credit assessment.",
        "Helped with credit due diligence on a large medium- to long-term bond investment in a leading internet company: pulled three years of audited statements, mapped them into the bank's credit template, built the three-year summary financials and tied out the three statements; worked out the core profitability and debt-service ratios (gross margin, ROE, leverage, interest coverage) and wrote the sections on operations and financials, external funding, and macro, policy and ESG risk.",
        "Researched 12 Belt and Road infrastructure projects across Southeast and South Asia (transport, ports, energy, industrial parks) for banking opportunities. Built a three-tier priority framework (pursue / niche entry / avoid), wrote an entry point and action plan for each project, and compiled the financing detail (size, debt–equity structure, lead banks and loan structure). Three judgements ran through it: FX convertibility is a hard constraint, cash flow is more credible than project size, and the parent-company relationship is the cross-sell angle.",
        "KYC and due diligence (ownership structure, UBO, source of funds); pulled data from S&P Capital IQ and broke a target company's financials down into the key metrics behind a colleague's credit rating.",
        "Entered a large tech group's Southeast Asia subsidiary's IFRS audited statements into the bank's overseas-financials credit system — account mapping and three-statement tie-out — and flagged the deterioration signals a lender cares about: the swing to a loss, cash burn, related-party fund flows.",
      ],
    },
    zh: {
      role: "客户经理实习生",
      org: "中国银行（新加坡分行）",
      unit: "环球公司金融部",
      dates: "2026.08 – 2026.11",
      place: "新加坡",
      lead: "在覆盖团队做信贷侧支持：行业研究、授信尽调、财务数据整理和 KYC。",
      points: [
        "独立撰写行业研究简报（泰国数据中心；社交媒体与数字广告）：价值链、市场规模与增速、竞争格局、政策激励，以及放贷方视角的风险分析，用于行业覆盖和授信评估。",
        "协助完成对某互联网龙头一笔大额中长期债券投资的授信尽调：独立提取近三年审计财报，按行内授信模板归集科目、编制三年财务简表并完成三表勾稽；测算毛利率、ROE、资产负债率、利息保障倍数等盈利与偿债指标，撰写经营财务、外部融资以及宏观 / 政策 / ESG 风险章节。",
        "调研东南亚与南亚 12 个「一带一路」重点基建项目（交通、港口、能源、产业园），评估商业银行可切入的机会：自建三梯队优先级框架（重点突破 / 细分切入 / 规避退出），逐项目写切入点与行动方案，整理配套融资底稿（投资规模、股债结构、牵头行与贷款结构）。分析里贯穿三条判断：外汇可兑换性是硬约束，现金流比工程规模更可信，母公司关系是交叉销售的抓手。",
        "参与 KYC 与尽职调查（股权结构、实际控制人、资金来源），用 S&P Capital IQ 收集数据，拆解某目标公司的财务报表，提取支持同事信用评级的关键指标。",
        "将某大型科技集团东南亚子公司的 IFRS 审计财报录入行内境外财报信贷系统，完成科目映射与三表勾稽，并从信贷视角标出财务恶化信号：由盈转亏、现金消耗、关联方资金往来。",
      ],
    },
  },
  {
    id: "smu",
    en: {
      role: "Bachelor of Business Management, Quantitative Finance",
      org: "Singapore Management University",
      unit: "Lee Kong Chian School of Business",
      dates: "Aug 2024 – May 2028",
      place: "Singapore",
      lead: "QS 2026: Accounting & Finance #50, Business & Management #39. Courses so far: finance, statistics, decision analysis, financial and management accounting, business law, operations, marketing.",
      points: [
        "Personal investing with a core–satellite approach: weekly DCA into an S&P 500 index fund, plus a few single names I follow.",
        "Took part in a Chinese F&B brand's overseas expansion project: franchise structure, cross-border supply chain, site selection and pricing.",
        "Produce a Mandarin podcast on my own, from recording to publishing.",
      ],
    },
    zh: {
      role: "工商管理学士 · 量化金融",
      org: "新加坡管理大学",
      unit: "李光前商学院",
      dates: "2024.08 – 2028.05",
      place: "新加坡",
      lead: "QS 2026 学科排名：会计与金融第 50，商业与管理第 39。已修课程：金融学、统计学、决策分析、财务会计、管理会计、商法、运营管理、市场营销。",
      points: [
        "个人投资采用「核心—卫星」框架：每周定投标普 500 指数基金，外加几只自己跟踪的个股。",
        "参与一个中国餐饮品牌的海外扩张项目，接触加盟结构、跨境供应链、选址和定价。",
        "独立制作一档中文播客，从录制到发布。",
      ],
    },
  },
]

export const skills = [
  {
    en: { group: "Analysis", items: ["Financial statement analysis", "Valuation: DCF, DDM, P/E, P/B", "Credit metrics, three-statement tie-out", "Sensitivity and scenario tables"] },
    zh: { group: "分析", items: ["财务报表分析", "估值：DCF、DDM、P/E、P/B", "信贷指标、三表勾稽", "敏感性与情景分析"] },
  },
  {
    en: { group: "Research", items: ["Sector briefs and market sizing", "KYC: ownership, UBO, source of funds", "Competitor benchmarking", "Support decks and documentation"] },
    zh: { group: "研究", items: ["行业简报与市场规模测算", "KYC：股权、实控人、资金来源", "竞品对标", "支持材料与文档"] },
  },
  {
    en: { group: "Tools", items: ["S&P Capital IQ", "Excel: modelling, pivot tables, regression", "PowerPoint", "Google Suite"] },
    zh: { group: "工具", items: ["S&P Capital IQ", "Excel：建模、数据透视、回归", "PowerPoint", "Google Suite"] },
  },
  {
    en: { group: "Currently", items: ["CFA Level I, Nov 2026", "Bloomberg Market Concepts, 2026", "Sector work: Thailand data centres, digital ads"] },
    zh: { group: "进行中", items: ["CFA 一级，2026 年 11 月", "Bloomberg 市场概念证书，2026", "行业研究：泰国数据中心、数字广告"] },
  },
]

const img = (id, n) => `./work/img/${id}/${String(n).padStart(2, "0")}.jpg`

export const works = [
  {
    id: "heineken",
    no: "01",
    widget: "scenarios",
    slides: [{ n: 1, src: img("heineken", 1) }],
    en: {
      title: "Heineken N.V.",
      kind: "Equity research",
      dek: "Equity research report on Heineken with a BUY recommendation: target price €75.23 against a market price of €68.08, an 11% upside.",
      preview: "Equity research on Heineken. Three-stage DDM, DCF and trading comps; BUY with a €75.23 target.",
      stamp: "BUY",
      figure: "€75.23",
      figureLabel: "Target price, DDM base case",
      meta: [["Course", "FNCE101 Finance"], ["When", "Oct – Nov 2025"], ["Team", "Group of 5"], ["My part", "P/E and DDM model, BEIA adjustments, sensitivity tables"]],
      stats: [["Market price", "€68.08"], ["Target price", "€75.23"], ["Upside", "11%"], ["Cost of equity", "6.73%"]],
      captions: {
        1: "Cover: BUY, target €75.23 vs market €68.08",
      },
      sections: [
        {
          h: "Background",
          p: "A full equity research report for our Finance course: company and industry overview, ESG review, ratio analysis against AB InBev and the industry, financing analysis (dividend policy, leverage, WACC) and valuation.",
        },
        {
          h: "Valuation",
          p: "The main method was a three-stage dividend discount model: 10.5% growth in 2025–2028 (buyback-driven EPS growth), 7.0% in 2029–2031, 3.3% terminal. Payout ratio set at 36%, within Heineken's 30–40% policy. That gives €75.23. A bear case at 30% payout gives €62.62 (−8%); a bull case at 40% gives €83.50 (+23%). We also ran a DCF (€104.43 at a 5.72% WACC) and trading comps (€70.8–74.1). Both pointed the same way, so we kept the DDM figure as the published target.",
        },
        {
          h: "My part",
          p: "I built the Excel model for the P/E and DDM valuation, separated underlying profit (BEIA) from reported net profit so the growth rates were not distorted by one-off items, and ran the sensitivity tables on payout ratio, cost of equity and terminal growth.",
        },
      ],
      widgetTitle: "Target price by payout ratio (market price €68.08)",
      scenarios: [
        { label: "Bear · 30% payout", value: "€62.62", delta: "−8%" },
        { label: "Base · 36% payout", value: "€75.23", delta: "+11%" },
        { label: "Bull · 40% payout", value: "€83.50", delta: "+23%" },
      ],
    },
    zh: {
      title: "Heineken N.V.",
      kind: "股权研究",
      dek: "喜力（Heineken）股权研究报告，给出买入评级：目标价 €75.23，对比市价 €68.08，上行空间 11%。",
      preview: "喜力股权研究。三阶段 DDM、DCF 与相对估值；买入，目标价 €75.23。",
      stamp: "买入",
      figure: "€75.23",
      figureLabel: "目标价，DDM 基准情景",
      meta: [["课程", "FNCE101 金融学"], ["时间", "2025.10 – 11"], ["团队", "5 人小组"], ["我负责", "P/E 与 DDM 模型、BEIA 调整、敏感性分析"]],
      stats: [["市价", "€68.08"], ["目标价", "€75.23"], ["上行空间", "11%"], ["权益成本", "6.73%"]],
      captions: {
        1: "封面：买入，目标价 €75.23 vs 市价 €68.08",
      },
      sections: [
        {
          h: "背景",
          p: "金融学课程的完整股权研究报告：公司与行业概况、ESG 评估、与百威英博及行业平均的比率分析、融资分析（股利政策、杠杆、WACC）和估值。",
        },
        {
          h: "估值",
          p: "主要方法是三阶段股利折现模型：2025–2028 年增速 10.5%（回购推动的 EPS 增长），2029–2031 年 7.0%，永续 3.3%。分红率取 36%，在喜力 30–40% 的政策区间内，得出 €75.23。悲观情景（30% 分红）为 €62.62（−8%），乐观情景（40%）为 €83.50（+23%）。另外做了 DCF（WACC 5.72%，得 €104.43）和相对估值（€70.8–74.1），方向一致，所以对外目标价采用 DDM 的结果。",
        },
        {
          h: "我负责的部分",
          p: "搭建 P/E 与 DDM 估值的 Excel 模型；把经营利润（BEIA）和报表净利润分开，避免一次性项目扭曲增速；做分红率、权益成本、永续增速的敏感性表。",
        },
      ],
      widgetTitle: "不同分红率下的目标价（市价 €68.08）",
      scenarios: [
        { label: "悲观 · 分红率 30%", value: "€62.62", delta: "−8%" },
        { label: "基准 · 分红率 36%", value: "€75.23", delta: "+11%" },
        { label: "乐观 · 分红率 40%", value: "€83.50", delta: "+23%" },
      ],
    },
  },
  {
    id: "telco",
    no: "02",
    widget: "compare",
    slides: [{ n: 1, src: img("telco", 1) }],
    en: {
      title: "StarHub vs Singtel",
      kind: "Financial statement analysis",
      dek: "Side-by-side analysis of Singapore's two main telcos from their FY2023 / FY2024 annual reports, ending in an investment recommendation.",
      preview: "Financial statement analysis of two Singapore telcos, section by section, from cash flow to equity.",
      stamp: "ACCT",
      figure: "21.0% vs 3.15%",
      figureLabel: "Return on equity, StarHub vs Singtel",
      meta: [["Course", "ACCT101 Financial Accounting"], ["When", "Mar – Apr 2025"], ["Team", "Group of 9"], ["My part", "Cash flow statement and equity sections, ratio analysis"]],
      stats: [["ROE", "21.0% vs 3.15%"], ["Receivables turnover", "9.11x vs 2.82x"], ["Collection period", "40 vs 129 days"], ["PER", "13.3x vs 49.8x"]],
      captions: {
        1: "Cover",
      },
      sections: [
        {
          h: "Background",
          p: "For Financial Accounting we compared StarHub (FY ending Dec 2023) and Singtel (FY ending Mar 2024) using their annual reports. We went through each part of the statements — cash flow, receivables, inventory, long-term assets, current and long-term liabilities, equity — and calculated the standard ratios for each.",
        },
        {
          h: "What we found",
          p: "StarHub collects receivables much faster (turnover 9.11x vs 2.82x; 40 days vs 129), has a higher profit margin, asset turnover and ROA, and its interest coverage improved sharply as EBIT recovered. Singtel has the stronger quick ratio (1.26 vs 0.96) and far more cash. Singtel's net income fell 64% that year, which pushed ROE down to 3.15% and PER up to 49.8x; StarHub's profit doubled, ROE rose to 21% and PER was 13.3x. On the ratios StarHub looked better. The group's final recommendation went with Singtel, based on share price performance and scale.",
        },
        {
          h: "My part",
          p: "I did the cash flow statement analysis (operating, investing and financing trends; restricted cash reconciliation) and the stockholders' equity section (ROE, EPS, book value per share, PER, PBR), and contributed to the final comparison.",
        },
      ],
      widgetTitle: "Side by side",
      compare: {
        left: "StarHub",
        right: "Singtel",
        rows: [
          ["Return on equity", "21.0%", "3.15%"],
          ["Price / earnings", "13.3x", "49.8x"],
          ["Receivables turnover", "9.11x", "2.82x"],
          ["Collection period", "40 days", "129 days"],
          ["Times interest earned", "4.79x", "2.16x"],
          ["Quick ratio", "0.96", "1.26"],
        ],
      },
    },
    zh: {
      title: "星和 vs 新电信",
      kind: "财务报表分析",
      dek: "基于 FY2023 / FY2024 年报，对新加坡两大电信公司做逐项财报对比，最后给出投资建议。",
      preview: "两家新加坡电信公司的财报分析，从现金流到股东权益逐项对比。",
      stamp: "ACCT",
      figure: "21.0% vs 3.15%",
      figureLabel: "净资产收益率，星和 vs 新电信",
      meta: [["课程", "ACCT101 财务会计"], ["时间", "2025.03 – 04"], ["团队", "9 人小组"], ["我负责", "现金流量表与股东权益部分、比率分析"]],
      stats: [["ROE", "21.0% vs 3.15%"], ["应收账款周转", "9.11x vs 2.82x"], ["回款天数", "40 天 vs 129 天"], ["市盈率", "13.3x vs 49.8x"]],
      captions: {
        1: "封面",
      },
      sections: [
        {
          h: "背景",
          p: "财务会计课程项目。用年报对比星和（财年截至 2023 年 12 月）和新电信（财年截至 2024 年 3 月），把报表每一部分——现金流、应收、存货、长期资产、流动与长期负债、股东权益——逐项过一遍，并计算对应的常用比率。",
        },
        {
          h: "结论",
          p: "星和回款快得多（周转 9.11x vs 2.82x；40 天 vs 129 天），利润率、资产周转率和 ROA 都更高，随 EBIT 修复利息保障倍数也明显改善。新电信速动比率更强（1.26 vs 0.96），现金也多得多。新电信当年净利润下滑 64%，ROE 被压到 3.15%，市盈率升到 49.8x；星和利润翻倍，ROE 升到 21%，市盈率 13.3x。单看比率星和更好，小组最终建议基于股价表现和规模选择了新电信。",
        },
        {
          h: "我负责的部分",
          p: "现金流量表分析（经营、投资、融资三项趋势；受限现金的勾稽）和股东权益部分（ROE、EPS、每股净资产、PER、PBR），并参与最后的综合对比。",
        },
      ],
      widgetTitle: "并排对比",
      compare: {
        left: "星和",
        right: "新电信",
        rows: [
          ["净资产收益率", "21.0%", "3.15%"],
          ["市盈率", "13.3x", "49.8x"],
          ["应收账款周转", "9.11x", "2.82x"],
          ["回款天数", "40 天", "129 天"],
          ["利息保障倍数", "4.79x", "2.16x"],
          ["速动比率", "0.96", "1.26"],
        ],
      },
    },
  },
  {
    id: "zeroq",
    no: "03",
    widget: "mix",
    slides: [{ n: 1, src: img("zeroq", 1) }],
    en: {
      title: "ZeroQ",
      kind: "Marketing plan",
      dek: "A marketing plan for a healthy lunch service in Singapore's CBD: order in an app, collect from a smart locker in the office lobby.",
      preview: "Marketing plan for a CBD lunch service: survey, positioning, 4P and a $100k first-year budget.",
      stamp: "MKTG",
      figure: "82%",
      figureLabel: "Survey respondents likely to try it",
      meta: [["Course", "MKTG101 Marketing"], ["When", "2025"], ["Team", "Individual presentation"], ["My part", "Survey and interviews, segmentation, 4P, year-one budget"]],
      stats: [["Price per bowl", "$11.90 – 12.90"], ["Subscription", "$99 for 10 meals"], ["Year-one budget", "$100,000"], ["Target CAC", "about $20"]],
      captions: {
        1: "Cover",
      },
      sections: [
        {
          h: "The idea",
          p: "CBD lunch queues run 15–20 minutes; hawker food has no nutrition information; salad bars are slow and expensive. ZeroQ is a customisable grain bowl with macros shown in the app, ordered ahead and collected from a temperature-controlled locker in the office lobby. Target customers: professionals aged 20–40 around Raffles Place, Tanjong Pagar and Marina Bay.",
        },
        {
          h: "The plan",
          p: "Price at $11.90–12.90 per bowl, below typical delivery, with a $99 ten-meal pass. Lockers in Grade-A office lobbies (CapitaGreen, Guoco Tower, MBFC), supplied by a cloud kitchen just outside the CBD and filled by 11:30 each day. Promotion budget split: 40% digital (LinkedIn, TikTok / Instagram, search), 25% offline activation, 20% influencers and PR, 15% corporate outreach. Goal: 5,000 active users in year one at roughly $20 per user.",
        },
        {
          h: "My part",
          p: "I ran the survey and interviews, wrote the segmentation and competitor analysis, built the 4P and the budget, and presented the deck.",
        },
      ],
      widgetTitle: "Marketing mix",
      mix: [
        ["Product", "Customisable grain bowls; protein, carbs and fat shown in the app and printed on the packaging."],
        ["Price", "$11.90–12.90 per bowl. ZeroPass: $99 for ten meals, about $9.90 each."],
        ["Place", "Smart lockers in Grade-A office lobbies, supplied by a cloud kitchen outside the CBD, filled by 11:30."],
        ["Promotion", "LinkedIn ads to analysts and HR, MRT street teams, micro-influencers, corporate wellness partnerships."],
      ],
    },
    zh: {
      title: "ZeroQ",
      kind: "营销方案",
      dek: "面向新加坡 CBD 的健康午餐服务营销方案：App 下单，到写字楼大堂的智能柜取餐。",
      preview: "CBD 午餐服务的营销方案：调研、定位、4P，以及 10 万新元的首年预算。",
      stamp: "MKTG",
      figure: "82%",
      figureLabel: "问卷受访者表示愿意尝试",
      meta: [["课程", "MKTG101 市场营销"], ["时间", "2025"], ["团队", "个人路演"], ["我负责", "问卷与访谈、市场细分、4P、首年预算"]],
      stats: [["单碗价格", "$11.90 – 12.90"], ["订阅", "$99 / 10 餐"], ["首年预算", "$100,000"], ["目标获客成本", "约 $20"]],
      captions: {
        1: "封面",
      },
      sections: [
        {
          h: "想法",
          p: "CBD 午餐要排 15–20 分钟队；小贩中心没有营养信息；沙拉店又慢又贵。ZeroQ 是可定制的谷物碗，App 里显示宏量营养，提前下单，到写字楼大堂的恒温柜取。目标客群是莱佛士坊、丹戎巴葛、滨海湾一带 20–40 岁的白领。",
        },
        {
          h: "方案",
          p: "单碗定价 $11.90–12.90，低于常见外送；另有 $99 十餐的订阅。柜子放在甲级写字楼大堂（CapitaGreen、Guoco Tower、MBFC），由 CBD 外围的中央厨房供货，每天 11:30 前补满。推广预算分配：数字渠道 40%（LinkedIn、TikTok / Instagram、搜索），线下地推 25%，KOL 与公关 20%，企业合作 15%。目标：首年 5,000 名活跃用户，获客成本约 $20。",
        },
        {
          h: "我负责的部分",
          p: "问卷和访谈、市场细分和竞品分析、4P 和预算，以及最后的路演。",
        },
      ],
      widgetTitle: "营销组合",
      mix: [
        ["产品", "可定制谷物碗；蛋白质、碳水、脂肪在 App 显示并印在包装上。"],
        ["价格", "单碗 $11.90–12.90。ZeroPass 订阅 $99 十餐，约 $9.90 一餐。"],
        ["渠道", "甲级写字楼大堂智能柜，CBD 外围中央厨房供货，11:30 前补满。"],
        ["推广", "LinkedIn 投放分析师与 HR，地铁口地推，KOL，企业健康福利合作。"],
      ],
    },
  },

  {
    id: "jetstar",
    no: "04",
    widget: "levers",
    slides: [{ n: 1, src: img("jetstar", 1) }],
    en: {
      title: "Jetstar Asia",
      kind: "Statistics project",
      dek: "Survey-based study of what drives customer satisfaction at Jetstar Asia, compared with AirAsia and Tigerair.",
      preview: "Customer satisfaction study for Jetstar Asia: regression across service factors and a comparison with two competitors.",
      stamp: "STAT",
      figure: "r = 0.64",
      figureLabel: "Comfort vs overall satisfaction",
      meta: [["Course", "STAT101 Introductory Statistics"], ["When", "Nov 2024"], ["Team", "Group of 7"], ["My part", "Correlation and regression analysis, confidence intervals"]],
      stats: [["Overall satisfaction", "4.57 / 7"], ["Comfort, r", "0.64"], ["Ease of booking, r", "0.63"], ["Confidence level", "95%"]],
      captions: {
        1: "Cover",
      },
      sections: [
        {
          h: "Background",
          p: "We used survey data on Jetstar Asia, AirAsia and Tigerair covering value for money, ease of booking, on-board experience, comfort and a few other factors, and asked which of them actually move overall satisfaction.",
        },
        {
          h: "What we found",
          p: "Comfort (r = 0.64) and ease of booking (r = 0.63) had the strongest correlation with overall satisfaction. Within comfort, legroom and seat comfort had the highest variance (SD 1.17 and 1.07), so some passengers were quite unhappy. Within booking, the 'easy-to-follow process' item was the least consistent (SD 1.01). At 95% confidence Jetstar's booking scores sat below both competitors. From the regression, one point higher on comfort adds about 0.65 to overall satisfaction; one point on booking adds about 0.78.",
        },
        {
          h: "Recommendation",
          p: "Improve legroom and headrests, and fix the booking flow: responsive layouts that work on every device, and automatic suggestion of the nearest available date when the chosen one is full.",
        },
      ],
      widgetTitle: "Correlation with overall satisfaction",
      levers: [
        ["Comfort", 0.64, "Legroom and seat comfort had the highest variance. One point higher adds about 0.65 to overall satisfaction."],
        ["Ease of booking", 0.63, "Least consistent item was the booking process itself. One point higher adds about 0.78."],
        ["On-board experience", 0.57, "Moderate. Contributes, but not the first lever."],
        ["Value for money", 0.5, "Moderate. Largely expected for a low-cost carrier."],
      ],
    },
    zh: {
      title: "捷星亚洲",
      kind: "统计学项目",
      dek: "基于问卷数据，研究影响捷星亚洲客户满意度的因素，并与亚航、虎航对比。",
      preview: "捷星亚洲客户满意度研究：对各服务因素做回归，并与两家竞争对手比较。",
      stamp: "STAT",
      figure: "r = 0.64",
      figureLabel: "舒适度与整体满意度的相关系数",
      meta: [["课程", "STAT101 统计学导论"], ["时间", "2024.11"], ["团队", "7 人小组"], ["我负责", "相关与回归分析、置信区间"]],
      stats: [["整体满意度", "4.57 / 7"], ["舒适度 r", "0.64"], ["预订便利 r", "0.63"], ["置信水平", "95%"]],
      captions: {
        1: "封面",
      },
      sections: [
        {
          h: "背景",
          p: "用捷星亚洲、亚航、虎航的问卷数据，覆盖性价比、预订便利、机上体验、舒适度等因素，研究哪些真正影响整体满意度。",
        },
        {
          h: "结论",
          p: "舒适度（r = 0.64）和预订便利（r = 0.63）与整体满意度相关性最强。舒适度里，腿部空间和座椅舒适的方差最大（SD 1.17 和 1.07），说明有一部分乘客很不满意。预订里，「流程是否容易跟」这一项最不稳定（SD 1.01）。在 95% 置信水平下，捷星的预订评分低于两家竞品。按回归结果，舒适度每提高 1 分，整体满意度约提高 0.65；预订便利每提高 1 分约提高 0.78。",
        },
        {
          h: "建议",
          p: "改善腿部空间和头枕；修复预订流程——各类设备上的响应式布局，以及首选日期满员时自动推荐最近可订日期。",
        },
      ],
      widgetTitle: "与整体满意度的相关系数",
      levers: [
        ["舒适度", 0.64, "腿部空间和座椅舒适方差最大。每提高 1 分，整体满意度约提高 0.65。"],
        ["预订便利", 0.63, "最不稳定的是预订流程本身。每提高 1 分约提高 0.78。"],
        ["机上体验", 0.57, "中等相关。有贡献，但不是首要杠杆。"],
        ["性价比", 0.5, "中等相关。对廉航来说基本是默认预期。"],
      ],
    },
  },  {
    id: "resumeai",
    no: "05",
    widget: null,
    slides: [
      { n: 1, src: "./work/resumeai-cover.png" },
      { n: 2, src: "./work/resumeai-detail.png" },
    ],
    en: {
      title: "ResumeAI",
      kind: "Personal project",
      dek: "An AI resume tool — paste a target job description, upload your resume, and the AI rewrites it to fit the role. Built end to end, on my own.",
      preview: "An AI resume tool — paste a target job description, upload your resume, and the AI rewrites it to fit the role. Built end to end, on my own.",
      stamp: "AI",
      figure: "AI resume tool",
      figureLabel: "2025 · Solo build",
      eyebrow: "Personal project · Vibe coding",
      meta: [["Type", "Personal project (vibe coding)"], ["When", "2025"], ["Team", "Solo"], ["My part", "Everything: product design, front end, back end, AI integration"]],
      stats: [],
      captions: {
        1: "ResumeAI landing page: BEFORE / AFTER cards around the headline",
        2: "Input screen: target JD, resume upload, project files, notes",
      },
      sections: [
        {
          h: "The idea",
          p: "While job hunting I noticed the same resume performs very differently for different roles, and rewriting it by hand for each JD is slow and tedious. ResumeAI lets you paste the target JD and upload your resume; the AI parses the role requirements, rewrites your experience for that role, and outputs a closer-fitting version you can export straight to PDF.",
        },
        {
          h: "What I built",
          p: "The whole flow works end to end: landing page, JD parsing, resume upload, AI generation and PDF export. The design is dark and restrained, with a BEFORE / AFTER comparison to show the rewrite at a glance.",
        },
        {
          h: "Looking back",
          p: "I later shelved it on purpose. What I wanted was to fine-tune the content at any time, as if chatting with the AI, while still reliably producing a document in a fixed format. The technology at the time couldn't do both well, so it fell short of the experience I had in mind and I paused it. It was the first product I took all the way through, and the pitfalls and judgement calls from it carried into the projects that followed.",
        },
      ],
    },
    zh: {
      title: "ResumeAI（来速米）",
      kind: "个人项目",
      dek: "一个 AI 改简历工具：粘贴目标岗位 JD、上传简历，AI 按岗位重写并生成匹配版本。从想法到能跑的产品，自己一个人做。",
      preview: "一个 AI 改简历工具：粘贴目标岗位 JD、上传简历，AI 按岗位重写并生成匹配版本。从想法到能跑的产品，自己一个人做。",
      stamp: "AI",
      figure: "AI 改简历",
      figureLabel: "2025 · 独立完成",
      eyebrow: "个人项目 · Vibe coding",
      meta: [["类型", "个人项目（vibe coding）"], ["时间", "2025"], ["团队", "独立完成"], ["我负责", "全部——产品设计、前后端、AI 集成"]],
      stats: [],
      captions: {
        1: "ResumeAI 落地页：标题两侧是 BEFORE / AFTER 卡片",
        2: "输入页：目标岗位 JD、简历上传、项目文件、补充说明",
      },
      sections: [
        {
          h: "想法",
          p: "求职时发现同一份简历投不同岗位效果差很多，手动按 JD 改又慢又烦。ResumeAI 让你贴上目标 JD、上传原简历，AI 解析岗位要求后把经历按这个岗位重写，输出更贴合的一版，可直接导出 PDF。",
        },
        {
          h: "做了什么",
          p: "落地页、JD 解析、简历上传、AI 生成、PDF 导出整条流程都跑通了。设计走暗色、克制，用 BEFORE/AFTER 对比直观展示改写效果。",
        },
        {
          h: "复盘",
          p: "后来主动搁置了：我想要的是能像跟 AI 对话一样随时微调内容、又能稳定输出规定格式的文档，但当时的技术做不到两者兼顾，达不到我预期的体验，就先停了。它是我第一个完整跑通的产品，踩过的坑和攒下的判断都带进了后面的项目。",
        },
      ],
    },
  },
]
